### ISSUE TITLE
Error: Uncaught RuntimeError: memory access out of bounds

### ISSUE THREAD

**Issue by rdebath** [yukikurage/brainf__k#7]
```
Hello World
Error: Uncaught RuntimeError: memory access out of bounds
```
[Bitwidth.b](https://github.com/rdebath/Brainfuck/blob/master/bitwidth.b#L160) seems to be crashing your interpreter.

Not debugged, but I suspect I might be tricking it into running off the start of the array by preparing to read that memory, but skipping past at the last moment.

**Comment by yukikurage** [comment]
Thanks for the report.

If it is running correctly, the contents of its loop will never be executed, so there will be no error, correct?

Perhaps the problem is that the loop is converted to multiply when it is determined that it is a loop representing multiplication, so it is executed even if the current cell value is 0.

**Comment by yukikurage** [comment]
8ca8c124b5ee753f9f91a38318f5bbe6d25321d4

Fixed. Thank you!
